jobs:
    start:
        requires: [~pr, ~commit]
        template: screwdriver/discord-rewrite-run
        steps:
            - preprebuild: 'Starting bot'
        secrets:
            - DISCORD_BOT_TOKEN