jobs:
    start:
        requires: [~pr, ~commit]
        template: screwdriver/python3-run
        steps:
            - preprebuild: pip install -U "yarl<1.2"
            - prebuild: python3 pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]